# Generated by Django 4.0.4 on 2022-04-20 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sobrevivente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('idade', models.PositiveIntegerField(blank=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('infectado', models.BooleanField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agua', models.PositiveIntegerField()),
                ('alimentacao', models.PositiveIntegerField()),
                ('medicacao', models.PositiveIntegerField()),
                ('municao', models.PositiveIntegerField()),
                ('sobrevivente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.sobrevivente')),
            ],
        ),
    ]
