# Generated by Django 4.0.4 on 2022-04-22 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sobrevivente_qant_denuncias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sobrevivente',
            old_name='qant_denuncias',
            new_name='quant_denuncias',
        ),
    ]
