# Generated by Django 4.0.4 on 2022-04-22 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_qant_denuncias_sobrevivente_quant_denuncias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('sobrevivente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.sobrevivente')),
            ],
        ),
    ]
